import AppText from '../../components/common/AppText';
import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, SafeAreaView, ActivityIndicator } from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { getPublicSchemes, getPublicScheme } from '../../features/anudan/schemeAPI';

const richText = value => String(value || '').replace(/<br\s*\/?>/gi, '\n').replace(/<\/(p|div|h[1-6]|li)>/gi, '\n').replace(/<li[^>]*>/gi, '• ').replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/\n\s*\n+/g, '\n\n').trim() || 'Not available';

export const schemes = [
  { id: 'pm-kisan', title: 'PM-KISAN Samman Nidhi', department: 'Ministry of Agriculture & Farmers Welfare', summary: 'Income support for eligible landholding farmer families.', benefits: 'Financial assistance is transferred directly to the registered bank account.', eligibility: 'Eligible landholding farmer family with valid Aadhaar and bank account.', application: 'Apply through the official PM-KISAN portal or nearest Common Service Centre.' },
  { id: 'pmfby', title: 'Pradhan Mantri Fasal Bima Yojana', department: 'Ministry of Agriculture & Farmers Welfare', summary: 'Crop insurance support against notified natural risks and crop losses.', benefits: 'Insurance protection for eligible crop loss according to scheme conditions.', eligibility: 'Farmers growing notified crops in notified areas with required documents.', application: 'Apply through the official crop-insurance portal, bank, or authorised service centre.' },
  { id: 'kcc', title: 'Kisan Credit Card', department: 'Department of Financial Services', summary: 'Timely institutional credit for cultivation and allied agricultural needs.', benefits: 'Access to revolving agricultural credit subject to bank approval.', eligibility: 'Farmers, tenant farmers, and eligible joint groups.', application: 'Submit the KCC application to a participating bank with required documents.' },
];

export default function AnudanYojanaScreen({ navigation }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { getPublicSchemes().then(result => setItems(result.schemes)).catch(() => setError('Unable to load schemes right now.')).finally(() => setLoading(false)); }, []);
  return <SafeAreaView style={styles.page}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={24} color="#111" /></TouchableOpacity><AppText style={styles.headerTitle}>Anudan Yojana</AppText><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content}><AppText style={styles.kicker}>Farmer support</AppText><AppText style={styles.heading}>Government schemes</AppText><AppText style={styles.subheading}>Explore benefits, eligibility, and application guidance.</AppText>{loading ? <ActivityIndicator color="#16A34A" size="large" /> : null}{error ? <AppText style={styles.error}>{error}</AppText> : null}{!loading && !error && !items.length ? <AppText style={styles.empty}>No schemes available.</AppText> : null}{items.map(scheme => <View key={scheme._id} style={styles.card}><View style={styles.cardHeading}><View style={styles.icon}><Ionicons name="business-outline" size={22} color="#16A34A" /></View><AppText style={styles.title}>{scheme.title}</AppText></View><AppText style={styles.department}>{(scheme.tags || []).join(' · ')}</AppText><AppText style={styles.summary}>{String(scheme.content || '').replace(/<[^>]+>/g, '').slice(0, 180)}</AppText><TouchableOpacity style={styles.details} onPress={() => navigation.navigate('AnudanYojanaDetails', { scheme })}><AppText style={styles.detailsText}>View details</AppText><Ionicons name="arrow-forward" size={17} color="#16A34A" /></TouchableOpacity></View>)}</ScrollView></SafeAreaView>;
}

export function AnudanYojanaDetails({ navigation, route }) { const initial = route.params?.scheme || {}; const [scheme, setScheme] = useState(initial); useEffect(() => { getPublicScheme(initial.slug || initial._id).then(setScheme).catch(() => {}); }, [initial.slug, initial._id]); return <SafeAreaView style={styles.page}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={24} color="#111" /></TouchableOpacity><AppText style={styles.headerTitle}>Scheme Details</AppText><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content}><AppText style={styles.heading}>{scheme.title}</AppText><AppText style={styles.department}>{(scheme.tags || []).join(' · ')}</AppText>{[['Overview', scheme.content], ['Benefits', scheme.benefits], ['Eligibility', scheme.eligibility], ['How to apply', scheme.applicationProcess], ['Required documents', scheme.requiredDocuments]].map(([label, value]) => <View key={label} style={styles.detailCard}><AppText style={styles.detailLabel}>{label}</AppText><AppText style={styles.detailText}>{richText(value)}</AppText></View>)}</ScrollView></SafeAreaView>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F5F7F3' }, header: { height: 100, paddingHorizontal: 20, paddingTop: 35, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFF' }, headerTitle: { fontSize: 18, fontWeight: '700', color: '#111' }, content: { padding: 18, paddingBottom: 40 }, kicker: { color: '#16A34A', fontWeight: '700', marginBottom: 5 }, heading: { fontSize: 25, fontWeight: '800', color: '#111', marginBottom: 6 }, subheading: { color: '#667', marginBottom: 18 }, card: { backgroundColor: '#FFF', borderRadius: 18, padding: 16, marginBottom: 14, elevation: 2 }, cardHeading: { flexDirection: 'row', alignItems: 'center' }, icon: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#E8F8EC', alignItems: 'center', justifyContent: 'center', marginRight: 10 }, title: { flex: 1, fontSize: 17, fontWeight: '700', color: '#111' }, department: { color: '#16A34A', fontSize: 12, marginTop: 10 }, summary: { color: '#667', lineHeight: 20, marginTop: 8 }, details: { flexDirection: 'row', alignItems: 'center', marginTop: 14, gap: 7 }, detailsText: { color: '#16A34A', fontWeight: '700' }, detailCard: { backgroundColor: '#FFF', borderRadius: 16, padding: 16, marginTop: 12 }, detailLabel: { fontSize: 15, fontWeight: '700', color: '#16A34A', marginBottom: 7 }, detailText: { color: '#444', lineHeight: 22 } });
